# -*- coding: utf-8 -*-
"""Feed Forward Network with Keras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N5A2R7a78b_MB_FRrtZ8Q0ABiSZn1mpV
"""

import tensorflow as tf
import numpy as np

model = tf.keras.Sequential([
    tf.keras.Input(shape=(3,)),
    tf.keras.layers.Dense(2, activation='sigmoid'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.layers[0].set_weights([
    np.array([
        [0.2, 0.3],
        [0.4, 0.5],
        [0.6, 0.7]
    ]),
    np.array([0.5, 0.8])
])
model.layers[1].set_weights([
    np.array([
        [0.1],
        [0.2]
    ]),
    np.array([0.3])
])

x = np.array([[5, 10, 15]])
y = np.array([[1]])

output = model(x)
loss = (y - output.numpy()) ** 2

print("Final Output:", output.numpy())
print("Loss:", loss)

