# -*- coding: utf-8 -*-
"""Feed Forward Network with TensorFlow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJNYEiDhLakJMmTrWn5GJndpUOvmYl--
"""

import tensorflow as tf

x = tf.constant([[5., 10., 15.]])
y = tf.constant([[1.]])

w1 = tf.constant([
    [0.2, 0.3],
    [0.4, 0.5],
    [0.6, 0.7]
], dtype=tf.float32)

b1 = tf.constant([0.5, 0.8], dtype=tf.float32)

w2 = tf.constant([
    [0.1],
    [0.2]
], dtype=tf.float32)

b2 = tf.constant([0.3], dtype=tf.float32)

z1 = tf.matmul(x, w1) + b1
a1 = tf.sigmoid(z1)

z2 = tf.matmul(a1, w2) + b2
a2 = tf.sigmoid(z2)

loss = tf.square(y - a2)

print("Final Output:", a2.numpy())
print("Loss:", loss.numpy())