# -*- coding: utf-8 -*-
"""Feed Forward Network with PyTorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eACpePxSrBLBeQ5Cz9-gsGjs-848hRK5
"""

import torch
import torch.nn as nn

x = torch.tensor([[5., 10., 15.]])
y = torch.tensor([[1.]])

class FeedForwardNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(3, 2)
        self.fc2 = nn.Linear(2, 1)

        self.fc1.weight.data = torch.tensor([
            [0.2, 0.4, 0.6],
            [0.3, 0.5, 0.7]
        ])
        self.fc1.bias.data = torch.tensor([0.5, 0.8])

        self.fc2.weight.data = torch.tensor([[0.1, 0.2]])
        self.fc2.bias.data = torch.tensor([0.3])

    def forward(self, x):
        x = torch.sigmoid(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        return x

model = FeedForwardNN()

output = model(x)
loss = (y - output) ** 2

print("Final Output:", output.item())
print("Loss:", loss.item())

