# -*- coding: utf-8 -*-
"""Simple Feed Forward Network using numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqZ9YQbQxH6Vnx-rhwrTklcQHBR83uCQ
"""

import numpy as np
x = np.array([5, 10, 15])
w = np.array([[0.2, 0.3], [0.4, 0.5], [0.6, 0.7]])
b = np.array([0.5, 0.8])
z = np.dot(x,w)+b
print("output",z)
def sigmoid(x):
  return 1/(1+np.exp(-x))
a = sigmoid(z)
print("activated output:",a)
w2 = np.array([[0.1, 0.2]])
b2 = np.array([0.3])
z2 = np.dot(a,w2.T)+b2
a2 = sigmoid(z2)
print("final output:",a2)
y = 1
loss = (y-a2)**2
print("loss:",loss)
lr = 0.1
dloss_da2 = -2*(y-a2)
da2_dz2 = a2*(1-a2)
dz2_dw2 = a
grad_w2 = dloss_da2*da2_dz2*dz2_dw2
w2 = w2 -lr* grad_w2.reshape(2,1)
print("updtaed w2:",w2)

